.PHONY: proto-gen run-server run-client

proto-gen:
	protoc --go_out=. --go_opt=mod=github.com/imran4u/go-grpc --go-grpc_out=. --go-grpc_opt=paths=source_relative hello.proto

run-server:
	go run server/main.go

run-client:
	go run client/main.go